/** GENERATED from the scraped live site — do not hand-edit prose.
 *  Regenerate with scripts/extract-platform-data.py if the source changes.
 *
 *  Every agent carries the full Input / Output / Control triad, because an
 *  Evidence Card with a missing row is a broken component, not a sparse one. */

export type AgentDetail = {
  slug: string;
  name: string;
  audience: string;
  summary: string;
  input: string;
  output: string;
  control: string;
};
export type Module = { title: string; body: string };
export type Role = { title: string; body: string };
export type Faq = { q: string; a: string };

export type PlatformDetail = {
  agents: AgentDetail[];
  modules: Module[];
  roles: Role[];
  compliance: string[];
  faqs: Faq[];
};

export const detail: Record<string, PlatformDetail> = {
  medorbit: {
    agents: [
      { slug: "front-desk-voice", name: "Front-Desk Voice Agent", audience: "Reception",
        summary: "Answers every call in your hospital's name, resolves FAQs, and books appointments straight into your schedule.",
        input: "A patient calls at 20:40, after the front desk has closed.",
        output: "The agent answers in the hospital's name, offers the next three orthopaedics slots, and writes the booking into the live schedule.",
        control: "Booking tools are cryptographically signed; every call is logged." },
      { slug: "aftercare-voice", name: "Aftercare Voice Agent", audience: "Nursing",
        summary: "Calls every discharged patient on day 2 and day 7, checks recovery, and records structured outcomes.",
        input: "Day 2 after a discharge, the agent calls and works through the recovery script.",
        output: "A structured outcome is recorded against the patient. One answer indicates deterioration, and the call is escalated to nursing.",
        control: "Deterioration escalates to your staff — the agent never advises." },
      { slug: "ai-scribe", name: "AI Scribe", audience: "Doctors",
        summary: "Turns a recorded consultation into a structured clinical note, ready for the doctor to edit.",
        input: "A nine-minute consultation, recorded in the room.",
        output: "A structured note with history, examination, assessment and plan. The doctor edits two lines and signs.",
        control: "Nothing enters the chart without a clinician's signature." },
      { slug: "pre-consult-brief", name: "Pre-Consult Brief", audience: "Doctors",
        summary: "Builds a Patient-360 brief — visits, labs, meds, allergies, vitals trend — before the doctor walks in.",
        input: "The 09:15 appointment is about to start.",
        output: "A ten-second brief: last three visits, current medications, two allergies, HbA1c trending upward.",
        control: "Reads the record; never writes to it." },
      { slug: "consult-summary", name: "Consult Summary + Draft-Rx", audience: "Doctors",
        summary: "Drafts doctor and patient summaries plus a draft prescription, checked against drug interactions and telemedicine schedules.",
        input: "The consultation ends.",
        output: "A clinician summary, a plain-language patient summary, and a draft prescription with one interaction flagged for review.",
        control: "Prescriptions stay drafts until the doctor approves." },
      { slug: "result-explainer", name: "Result Explainer", audience: "Patients",
        summary: "Explains lab and imaging results in plain language in the patient portal, the moment they release.",
        input: "A lipid panel releases at 13:00.",
        output: "The portal shows the numbers alongside a plain-language explanation of what each one means for this patient.",
        control: "Guarded output; clinical questions route to your team." },
      { slug: "referral-triage", name: "Referral Triage Router", audience: "Referrals desk",
        summary: "Reads inbound referrals, drafts urgency and specialty, and chases missing information before the patient travels.",
        input: "An inbound cardiology referral arrives without an ECG attached.",
        output: "Urgency drafted, routed to cardiology, and the missing ECG requested from the referrer before the patient travels.",
        control: "A code-enforced floor stops the AI from ever downgrading urgency." },
      { slug: "denial-guard", name: "Denial Guard", audience: "Billing",
        summary: "Classifies why a claim was denied and drafts the appeal, within value and review thresholds you set.",
        input: "A claim is denied for a coding mismatch.",
        output: "The denial reason is classified and an appeal drafted with the supporting documentation attached, then queued for review.",
        control: "A biller approves every appeal before it leaves." },
      { slug: "queue-concierge", name: "Queue Concierge", audience: "Front office",
        summary: "Predicts wait times and proactively updates waiting patients on WhatsApp, rescuing slots before they walk.",
        input: "The 08:00 OPD queue is running 25 minutes behind.",
        output: "Waiting patients receive a WhatsApp update with the revised time. Two accept a later slot instead of leaving.",
        control: "Quiet hours respected; templated messages, AI-read replies." },
      { slug: "med-reconciliation", name: "Med Reconciliation", audience: "Pharmacy",
        summary: "Cross-checks medications against RxNorm and openFDA at every admission and discharge, and flags discrepancies.",
        input: "A patient's home medication list is entered on admission.",
        output: "Cross-checked against RxNorm and openFDA; two duplicates and one interaction are flagged.",
        control: "A pharmacist signs off every reconciliation." },
      { slug: "sahayak", name: "Sahayak", audience: "All staff",
        summary: "Renders patient communication into Hindi, Marathi, Kannada and more — and falls back to English rather than guess.",
        input: "A discharge instruction needs to reach a family who read Kannada.",
        output: "The instruction is rendered into Kannada. One clinical term has no confident rendering, so it stays in English rather than being guessed at.",
        control: "Back-translation QA samples every batch. Roles ## Who MedOrbit is for 8 roles, each with its own view — and an audit log that records who saw what." },
    ],
    modules: [
      { title: "Front office", body: "OPD and token queue, appointments and scheduler, registration and kiosk, patient portal, CRM and recall, queue displays." },
      { title: "Clinical", body: "EMR and clinical notes, e-prescribing, drug-interaction decision support, vaccinations, medical records and certificates, telehealth." },
      { title: "Diagnostics", body: "Lab (LIS) and QC, radiology with RIS/PACS link, collection centres, home collection, blood bank, critical-value alerts." },
      { title: "Pharmacy and supply", body: "Hospital and retail pharmacy, e-pharmacy delivery, controlled substances under NDPS, procurement, inventory and stores, biomedical assets." },
      { title: "Revenue cycle", body: "Billing and deposits, insurance and pre-authorisation, NHCX cashless claims, PM-JAY / CGHS / ESIC, GST e-invoicing with IRN, denials and TPA settlement." },
      { title: "Inpatient and governance", body: "IPD wards and beds, OT and surgery, emergency and triage, NABH/NABL indicators, compliance and audit, group HQ for chains." },
    ],
    roles: [
      { title: "Doctor", body: "Patient-360 brief before the consultation, AI scribe for the note, draft prescription checked for interactions — all signed by the clinician before anything enters the record." },
      { title: "Nurse", body: "Ward and bed management, triage, and the aftercare agent's day-2 and day-7 escalations arriving as actionable items." },
      { title: "Lab technician", body: "LIS with analyzer integration, QC workflows, and critical-value alerting that reaches the treating clinician." },
      { title: "Pharmacist", body: "Dispensing, NDPS registers, and medication reconciliation cross-checked against RxNorm and openFDA — signed off by a pharmacist every time." },
      { title: "Receptionist", body: "Token queue and scheduler, with the voice agent taking after-hours calls and the queue concierge messaging waiting patients." },
      { title: "Billing", body: "Revenue cycle end to end, with the denial agent classifying rejections and drafting appeals for a biller to approve." },
      { title: "Hospital administrator", body: "Compliance and audit surfaces, NABH/NABL indicators, cost caps per facility, and a kill switch for any agent." },
      { title: "Patient", body: "A separate portal for appointments, records and prescriptions, with lab results explained in plain language the moment they release." },
    ],
    compliance: ["ABDM / ABHA", "NHCX cashless claims", "FHIR R4 · HL7 v2", "NABH indicator reporting", "PM-JAY · CGHS · ESIC", "GST e-invoicing with IRN", "DLT-approved WhatsApp / SMS", "DPDP Act 2023", "AWS Mumbai (ap-south-1)"],
    faqs: [
      { q: "What is MedOrbit?", a: "MedOrbit is an AI-native hospital management system built for 23 types of Indian healthcare facility, from solo clinics to hospital chains. It runs OPD, IPD, lab, pharmacy, billing and over 100 modules on one platform, with 11 AI agents under clinician control." },
      { q: "What do the AI agents actually do?", a: "They answer inbound calls and book appointments, call discharged patients on day 2 and day 7, draft clinical notes from recorded consultations, prepare a Patient-360 brief before each consultation, explain lab results in plain language, triage inbound referrals, appeal denied claims, message waiting patients about delays, reconcile medications against RxNorm and openFDA, and render patient communication into Indian languages." },
      { q: "How is the AI kept safe?", a: "Seven controls ship in the platform: PHI is redacted before every model call, human sign-off is required by default, every AI action is written to an audit trail, offline evaluations gate releases, per-facility cost caps downshift the model automatically, each agent has an individual kill switch, and DPDP data requests are handled in-system. Identifiers are redacted before any AI call and customer data is not used to train models." },
      { q: "Is MedOrbit ABDM compliant?", a: "MedOrbit is ABDM-native, with ABHA creation and consent-based record sharing, and supports NHCX cashless claims, FHIR R4 and HL7 v2 interoperability, and PM-JAY, CGHS and ESIC claim flows. These are capability statements, not certification logos — certificates are published only when they exist." },
      { q: "Where is hospital data stored?", a: "In India. MedOrbit runs in AWS Mumbai (ap-south-1) under the DPDP Act 2023, with consent flows and data-request handling built into the platform." },
    ],
  },
  edvation: {
    agents: [
      { slug: "study-mentor", name: "Study Mentor", audience: "Students",
        summary: "Answers any question from the school's own textbook, with the page number attached.",
        input: "A student asks why the reaction is exothermic.",
        output: "An answer drawn from the school's own uploaded book, citing Science · Ch 4 · p. 87.",
        control: "If it is not in your book, the platform says so rather than guessing." },
      { slug: "voice-tutor", name: "Voice Tutor", audience: "Students",
        summary: "Takes spoken questions and answers aloud, grounded in the chapter, in the student's own language.",
        input: "A student speaks a doubt in Kannada during revision and interrupts partway through the answer.",
        output: "The tutor stops, takes the follow-up, and continues from the same page-cited source.",
        control: "Answers stay grounded in the uploaded chapter, never the open internet." },
      { slug: "listen-learn", name: "Listen & Learn", audience: "Students",
        summary: "Turns every chapter into narrated audio or a two-host podcast.",
        input: "A student selects Chapter 6 before the bus journey home.",
        output: "A nine-minute two-host podcast generated from that chapter's own text.",
        control: "Generated from the school's uploaded book, not from general knowledge." },
      { slug: "chapter-song", name: "Chapter Song", audience: "Students",
        summary: "Composes a song from the chapter, after a teacher approves the lyrics.",
        input: "A teacher requests a song for the water cycle.",
        output: "Lyrics are drafted for approval. Only once the teacher approves is the music composed.",
        control: "Approval happens before generation, not moderation after it." },
      { slug: "teacher-lesson-kit", name: "Teacher Lesson Kit", audience: "Teachers",
        summary: "Builds a five-artifact lesson kit from one sentence, grounded in the chapter.",
        input: "\"Photosynthesis, Class 7, one period.\"",
        output: "A lesson plan, slides, a worksheet, an exit ticket and homework — all drawn from the school's own chapter.",
        control: "Chapter-grounded; never fabricated from outside the book." },
      { slug: "quiz-generator", name: "AI Quiz Generator", audience: "Teachers",
        summary: "Generates board-ready questions tagged by board pattern and Bloom level.",
        input: "A teacher selects Chapter 12 and asks for twenty questions.",
        output: "Twenty questions tagged by difficulty and learning outcome, ready to assign as homework in two clicks.",
        control: "Textbook-grounded, with PDF and OCR intake for scanned material." },
      { slug: "socratic-practice", name: "Socratic Practice", audience: "Students",
        summary: "Gives hints, never answers — and flags the teacher when a student is genuinely stuck.",
        input: "A student asks for the answer three times in a row.",
        output: "Three progressively stronger hints, L1 through L3. The teacher then sees a stuck-flag for that student and that step.",
        control: "Anti-cheating by design — the answer is never given." },
      { slug: "writing-coach", name: "Writing Coach", audience: "Students",
        summary: "Coaches writing with anchored comments, and declines to write it for you.",
        input: "A student asks it to write the conclusion of their essay.",
        output: "It declines, and coaches the structure of a conclusion instead. Pasted text elsewhere in the essay is flagged to the teacher.",
        control: "No-ghostwrite guardrail, enforced in the product." },
      { slug: "school-copilot", name: "Ask School Copilot", audience: "Principals",
        summary: "Answers questions about the school from live operational data, with citation chips.",
        input: "\"Which Class 9 sections are below 80% attendance this month?\"",
        output: "An answer from live attendance data, each figure carrying a chip showing the record it came from.",
        control: "Answers from live school data, with the source of each number shown." },
      { slug: "in-app-assistant", name: "In-app Assistant", audience: "Everyone",
        summary: "Gives role-aware help on every screen, plus a spoken daily briefing.",
        input: "A new teacher on the gradebook screen asks how curving works.",
        output: "An answer scoped to that screen and to what a teacher is permitted to see.",
        control: "Role-aware — it will not explain a surface the user cannot access." },
      { slug: "memory-coach", name: "Memory Coach", audience: "Students",
        summary: "Schedules spaced repetition, compressed to the days remaining before the exam.",
        input: "Fourteen days remain before the Class 10 board exam.",
        output: "The revision schedule re-weights toward the three weakest chapters, and the class heatmap updates for the teacher.",
        control: "Mastery tracked per student; the class view is aggregate." },
      { slug: "teach-it-back", name: "Teach It Back", audience: "Students",
        summary: "Grades a student's own explanation against the book, quoting the pages they missed.",
        input: "A student explains Ohm's law aloud in their own words.",
        output: "A grade against the textbook, quoting the two sentences from the chapter they did not cover.",
        control: "Graded against the book, with page-cited quotes as evidence." },
      { slug: "memory-maps", name: "Memory Maps", audience: "Students",
        summary: "Turns a chapter into a mind-map where every node carries a page citation.",
        input: "A student opens Chapter 9 before a test.",
        output: "A downloadable map of the chapter. Tapping any node opens the page it came from.",
        control: "Every node is page-cited and traceable to the book." },
      { slug: "exam-readiness", name: "Exam Readiness", audience: "Students",
        summary: "Sets board-pattern papers and marks them the way an examiner would, step by step.",
        input: "A student completes a board-pattern maths paper.",
        output: "Step-marking with partial credit, and a marks-lost analysis: \"lost 2 marks at step 3 of the quadratic — a sign error.\"",
        control: "Examiner-style step-marking, not a single score." },
      { slug: "daily-sprint", name: "Daily Sprint", audience: "Students",
        summary: "Runs a three-minute daily practice ritual, with streaks and a weekly parent digest.",
        input: "A student opens the app for three minutes after school.",
        output: "Five questions, streak intact, and the result folded into Sunday's parent digest.",
        control: "Capped at three minutes by design." },
      { slug: "maths-mentor", name: "Maths Mentor", audience: "Students",
        summary: "Works through maths step by step and finds the first wrong step, not just the wrong answer.",
        input: "A student photographs a handwritten worked solution.",
        output: "Handwriting OCR reads the working and identifies the first step where it went wrong, then coaches from there.",
        control: "Socratic loop — the corrected step is not simply handed over." },
      { slug: "speak-coach", name: "Speak Coach", audience: "Students",
        summary: "Scores pronunciation in the browser, so a child's recording never leaves the device.",
        input: "A Telugu-medium learner reads a passage aloud.",
        output: "A pronunciation heatmap showing a consistent /v/–/w/ substitution, with targeted drills.",
        control: "Audio stays in the browser; recordings never leave the device." },
      { slug: "abacus-trainer", name: "Abacus Trainer", audience: "Students",
        summary: "Trains mental maths with spoken-answer grading, handwriting OCR and a hard screen-time cap.",
        input: "Dictation practice at competition speed.",
        output: "Answers graded from speech, paper sheets graded by OCR, and the session ends at the cap.",
        control: "Hard 25-minute screen-time cap." },
      { slug: "career-compass", name: "Career Compass", audience: "Students",
        summary: "Runs scenario interviews and produces a discussion kit for parents in 13 languages.",
        input: "A Class 10 student runs a scenario interview for a career they are curious about.",
        output: "A reflection for the student, and a discussion kit for the parent in Marathi.",
        control: "Exploratory — it suggests conversations, not decisions." },
      { slug: "science-lab", name: "Science Lab", audience: "Students",
        summary: "Runs predict-observe-explain against page-cited concept boards and simulations.",
        input: "A student is about to run a simulation.",
        output: "They must predict the outcome first, then explain the gap between prediction and observation.",
        control: "Concept boards are page-cited to the school's own chapter. Roles ## Who Edvation is for 6 roles, each with its own view — and an audit log that records who saw what." },
    ],
    modules: [
      { title: "Student information and enrolment", body: "Admissions and enrolment, student records, and the administrative spine the rest of the platform runs on." },
      { title: "Attendance and timetable", body: "Geofenced check-in, live attendance, timetabling and substitution, with instant parent alerts." },
      { title: "Gradebook and assessments", body: "Curves, GPA, blind grading and an appeals workflow, plus question banks, adaptive tests and proctoring." },
      { title: "Fees and finance", body: "Fee structures, collection, receipts and reconciliation, with payment reminders to parents in their own language." },
      { title: "Notifications and emergency broadcast", body: "One tap to every parent, plus the weekly AI digest that summarises a child's week with conversation starters." },
      { title: "Analytics, audit and security", body: "Early-warning signals for at-risk students, a full audit log, role-based access, and a global search across the estate." },
    ],
    roles: [
      { title: "Student", body: "A tutor that knows the exact textbook: ask any chapter a question, revise with spaced repetition, practise without being handed answers, and prepare with board-pattern papers marked step by step." },
      { title: "Teacher", body: "A five-artifact lesson kit from one sentence, board- and Bloom-aware quiz generation, examiner-style step-marking, a class misconception radar, and a stuck-flag inbox from Socratic Practice." },
      { title: "Parent", body: "A weekly digest in the home language with questions to ask at dinner, study streaks, consent controls, fees and payments — designed for a parent who does not read English." },
      { title: "Principal", body: "Ask the school anything in plain language and get an answer from live operational data with citation chips, plus early-warning signals and compliance surfaces." },
      { title: "Administrator", body: "Audit log, roles and permissions, global search, and the operational estate behind admissions, attendance and fees." },
      { title: "School", body: "The institution-level view: admissions, attendance and timetable, fees and finance, report cards, parent communication and the 20 teaching agents." },
    ],
    compliance: ["DPDP-ready consent flows", "Data in India (AWS Mumbai)", "Full audit trail", "No training on student data", "Your uploads stay yours", "CBSE · ICSE & ISC · IB · Cambridge · state boards"],
    faqs: [
      { q: "What is Edvation?", a: "Edvation is a complete school platform for Indian K-12 education — admissions, attendance, fees, timetable, assessments, report cards and parent communication — with 20 built-in AI agents that teach from the school's own uploaded textbooks." },
      { q: "Which boards does Edvation support?", a: "All of them. Edvation does not bundle textbooks; the school uploads its own books and PDFs, and the agents teach from those. CBSE, ICSE and ISC, IB, Cambridge and every state board work by construction, because there is no pre-licensed syllabus to outgrow." },
      { q: "How does Edvation stop the AI making things up?", a: "Every grounded AI answer carries the page number it came from, in the school's own uploaded textbook. A student, parent or teacher can open the printed book and check it. If something is not in the book, the platform says so rather than guessing." },
      { q: "Does it help students cheat?", a: "It is designed to prevent it. Socratic Practice gives a three-level hint ladder and then flags the teacher rather than giving the answer. Writing Coach declines requests to write the work and coaches structure instead, and pasted text is flagged to the teacher." },
      { q: "Is student data used to train models?", a: "No. Uploads stay private to the school, student data is not used to train models, and the platform runs in AWS Mumbai under DPDP-ready consent flows with a full audit trail." },
    ],
  },
  advohub: {
    agents: [
      { slug: "research-agent", name: "Citation-Grounded Research", audience: "Associates",
        summary: "Answers any Indian-law question with every citation verified against Indian Kanoon first.",
        input: "\"Can a director who resigned before the cheque was issued be held vicariously liable under Section 141 of the NI Act? Supreme Court and Delhi High Court only.\"",
        output: "An answer composed with per-claim citations. One authority cannot be resolved, so it is removed — and the answer says so.",
        control: "Fail-closed: an unverifiable authority is removed, never rendered with a caveat. Overruled or doubted judgments are flagged, not quietly cited." },
      { slug: "matter-copilot", name: "Matter Copilot", audience: "Senior associates",
        summary: "Chat with any case file — and let it take the action you approve.",
        input: "\"What's outstanding on this matter?\"",
        output: "An answer built only from the matter file and live tool results, each fact showing its source. A requested update becomes a proposal for approval.",
        control: "Never states a fact that did not come from the file; says \"not on file\" instead. Write tools create proposals a human must approve. Text inside documents is data, never instructions." },
      { slug: "hearing-prep-agent", name: "eCourts Hearing-Prep", audience: "Litigators",
        summary: "The evening before a listing: chronology, issues and the questions likely to come.",
        input: "A listing is scheduled for tomorrow morning.",
        output: "A brief assembling the chronology, the issues, and the questions likely to be asked — every order referenced by its date in the record.",
        control: "Any case citation not present verbatim in the input is stripped server-side. Empty lists stay empty rather than being filled with placeholders." },
      { slug: "drafting-agent", name: "Drafting Agent", audience: "Associates",
        summary: "Court-ready first drafts of petitions, written statements, replies and notices.",
        input: "A written statement is needed on a commercial suit.",
        output: "A draft built from the matter's own facts, in the firm's own voice. Anything missing appears as [FACT NEEDED: …].",
        control: "Interpolates only the facts provided — never invents names, dates, amounts or addresses." },
      { slug: "voice-intake-agent", name: "Vernacular Voice & WhatsApp Intake", audience: "Front desk",
        summary: "Takes client intake and status calls 24×7, in the language the client speaks.",
        input: "A prospective client messages in Marathi on WhatsApp at 22:00.",
        output: "The agent responds in Marathi, captures the intake, and records DPDP consent verbatim on the first substantive turn.",
        control: "Until identity is verified it will never confirm a number belongs to a client or reveal any case detail. No legal advice — it escalates to an advocate." },
      { slug: "contract-review-agent", name: "Contract Review & Redlining", audience: "Corporate practice",
        summary: "Clause-by-clause review and redlines against your firm's own playbook.",
        input: "A 40-page services agreement is uploaded for review.",
        output: "Clause-level redlines against the firm's playbook, with obligations extracted and scored.",
        control: "Every obligation quoted is a literal substring of the document. Base Indian-law checks always run — Contract Act §23 and §27, Arbitration Act §20 seat and venue, GST clause presence." },
      { slug: "matter-action-agent", name: "Proactive Matter Action", audience: "Everyone",
        summary: "Watches every matter and surfaces what it needs today, as cards you accept.",
        input: "The overnight pass runs across the firm's whole portfolio.",
        output: "A card surfaces a limitation deadline with the quote from the file that establishes it.",
        control: "A verbatim source quote must match the file or the deadline is rejected. Confidence below 0.6 is dropped; 0.6 to 0.8 is annotated for verification." },
      { slug: "billing-agent", name: "Billing & Timekeeping AI", audience: "Billing",
        summary: "Writes billing narrations and catches the billable time you forgot to record.",
        input: "The month's time entries are ready for invoicing.",
        output: "Narrations drafted for each entry, and unrecorded billable time surfaced for review.",
        control: "The model never computes money. Amount patterns are rejected on input and the output is re-scanned before it is shown." },
      { slug: "evidence-review-agent", name: "Bulk Evidence Review", audience: "Litigators",
        summary: "Reads, tags and summarises evidence sets of 50 to 500 files at a time.",
        input: "312 files are submitted as a single evidence set.",
        output: "Every file tagged and summarised, with a fact matrix assembled across the set.",
        control: "Every extracted fact carries a verbatim quote that must be a literal substring of the source. Facts whose quote does not match are dropped and counted." },
      { slug: "firm-knowledge-agent", name: "Firm Knowledge & Precedent", audience: "Everyone",
        summary: "\"Have we argued this before?\" — answered from your own firm's history.",
        input: "\"Have we run a §138 defence on a resigned-director point?\"",
        output: "An answer from the firm's own past drafts, memos and precedent, with the matters it came from.",
        control: "The ethical wall is pushed into the retrieval SQL, so barred matters are never retrieved — let alone shown — and re-applied before any text reaches a prompt. Roles ## Who AdvoHub is for 9 roles, each with its own view — and an audit log that records who saw what." },
    ],
    modules: [
      { title: "Case intelligence and court operations", body: "The matter file with parties, stages and a limitation clock computed rather than remembered; eCourts sync by CNR, cause lists, and clash detection across courtrooms rather than across dates." },
      { title: "Legal research and drafting", body: "Indian case law and statute searched semantically with every citation verified before it reaches you, and petitions, notices, replies and contracts drafted from the matter's own facts in the firm's own language." },
      { title: "Evidence management", body: "Evidence with a hash-chained chain of custody, Section 65B and BSA §63 certificates generated from it, and an admissibility score." },
      { title: "Client management and portal", body: "Intake, KYC via DigiLocker, and a separately-authenticated client portal that answers \"what is happening with my case?\" without a phone call." },
      { title: "Billing and finance", body: "Time, invoices and GST computed correctly — CGST and SGST within the state, IGST across it — plus BCI Rule 27 trust accounting and GSTR-1/3B outputs." },
      { title: "AI intelligence and platform", body: "The layer the ten agents run on: consent gating, citation verification, cost ceilings in rupees and an audit trail — on Indian data residency with tenant isolation at the query layer." },
    ],
    roles: [
      { title: "Managing partner", body: "The console the whole firm runs on, and the audit trail that proves it — with per-firm AI cost ceilings enforced in rupees." },
      { title: "Partner", body: "Oversight and the money: approvals, collections, and the matters that cannot be allowed to slip." },
      { title: "Senior associate", body: "Run matters end to end, with the agents doing the evening's assembly work — hearing briefs, chronologies and first drafts." },
      { title: "Associate", body: "The working lawyer's seat: assigned matters, verified research, and drafts that mark their own gaps rather than inventing facts." },
      { title: "Junior associate", body: "Real work with guardrails: supervised surfaces, no billing exposure, and research that cannot cite an unverified authority." },
      { title: "Intern", body: "The learning seat: read everything permitted, write nothing, cite properly — and the audit log records who saw what." },
      { title: "Paralegal", body: "The courts-and-filings seat: e-filing, cause lists and exhibits, with clash detection across courtrooms." },
      { title: "Front desk", body: "Reception and records, least-privileged by design, with the vernacular intake agent taking calls 24×7 in the client's language." },
      { title: "Client", body: "A separate portal with its own authentication and its own key — case status, documents, invoices and appointments, in English or Hindi." },
    ],
    compliance: ["DPDP Act 2023 (§6/§7 consent, §8(4) erasure)", "BSA 2023 §63 / IEA §65B", "BCI Rule 36 AI disclosure", "BCI Rule 27 trust accounts", "eCourts v3.0 official API", "GST · GSTR-1/3B · IRN e-invoicing", "Limitation Act 1963", "WCAG 2.1 AA", "AWS Mumbai (ap-south-1)"],
    faqs: [
      { q: "What is AdvoHub?", a: "AdvoHub is an AI-native legal practice platform for Indian advocates and law firms. It covers an engagement from intake to invoice across twelve modules, and adds ten purpose-built AI agents for research, hearing preparation, drafting, contract review, evidence review, intake, billing and firm knowledge." },
      { q: "How does AdvoHub prevent AI hallucinations?", a: "Every citation is verified against Indian Kanoon before it is displayed, and the citation graph is checked so anything overruled or doubted is flagged rather than quietly cited. A verification pass then removes any authority that cannot be resolved — fail-closed, so an unverifiable citation is stripped rather than rendered with a caveat." },
      { q: "What guardrails apply to the AI agents?", a: "Six apply to every agent without exception: citations verified against Indian Kanoon before you see them; DPDP consent gated fail-closed before any client data reaches a model; BCI Rule 36 disclosure on every AI-assisted output; agents propose and a human approves before anything is filed; per-firm cost ceilings enforced in rupees; and every invocation logged to the firm's audit trail." },
      { q: "Which languages does AdvoHub support?", a: "22 Indian languages, across drafting, voice, search and the client portal — built into the pipeline rather than translation added on top of an English one." },
      { q: "Where is case data stored?", a: "In India. Client and case data resides in AWS Mumbai (ap-south-1) with DPDP Act 2023 consent and erasure workflows, tenant isolation enforced at the query layer, and an append-only audit trail." },
      { q: "What does AdvoHub cost?", a: "Solo Advocate is ₹999 per month, Firm is ₹3,999 per seat per month, and Enterprise is quoted. Annual billing saves 20%, pricing is INR only and GST-inclusive on the invoice, and there is a 14-day trial with no card required. Each paid tier states its AI cost ceiling, so the monthly figure is the figure." },
    ],
  },
  trustproperty: {
    agents: [
      { slug: "trustline-concierge", name: "TrustLine Concierge", audience: "Tenants, buyers and owners",
        summary: "Answers questions on every listing 24×7, in text or voice, and books the site visit.",
        input: "At 11:40 PM a tenant asks about the deposit.",
        output: "TrustLine answers from the listing — text or voice, English, हिन्दी or Hinglish — checks the owner's calendar, and books Saturday 11 AM.",
        control: "Answers only from that listing's verified facts, with a note explaining why it said what it said." },
      { slug: "lead-intelligence", name: "Lead Intelligence", audience: "Agents",
        summary: "Scores every enquiry and shows the reasoning behind the score.",
        input: "A new enquiry lands on a three-bedroom listing.",
        output: "Scored 82/100 HOT in seconds — with reasons: asked to visit (+25), stated budget (+20), moving this month (+20).",
        control: "The factor breakdown ships with every score; the number is never shown alone." },
      { slug: "listing-intake", name: "Listing Intake", audience: "Owners",
        summary: "Turns spoken description into a filled listing form, and names what is still missing.",
        input: "An owner speaks 60 seconds of Hinglish.",
        output: "The form fills itself — and lists the two fields still missing.",
        control: "It reports its own gaps rather than inventing values for them." },
      { slug: "property-enrichment", name: "Property Enrichment", audience: "Owners",
        summary: "Ranks listing photos, picks the cover, and tells you which shot is missing.",
        input: "An owner uploads eleven photos.",
        output: "It ranked your photos, picked the best cover — and told you the kitchen photo is missing.",
        control: "Suggests; the owner chooses." },
      { slug: "retro-correction", name: "Retro-Correction", audience: "Agents",
        summary: "Notices when one person appears as two leads, merges them, and re-scores.",
        input: "The same visitor returns on a different device.",
        output: "The AI noticed, merged the lead, and re-scored it.",
        control: "Merges are visible to the agent and reversible." },
      { slug: "pipeline-watchdog", name: "Pipeline Watchdog", audience: "Agents",
        summary: "Flags stalled deals and suggests the nudge that restarts them.",
        input: "A deal sits quiet for nine days at Offer stage.",
        output: "It gets flagged — with a suggested nudge the agent sends in one tap.",
        control: "The agent sends it; the watchdog never messages a client directly." },
      { slug: "ad-factory", name: "Ad Factory", audience: "Agents",
        summary: "Writes, launches and optimises listing advertising in English and Hindi.",
        input: "A new listing needs a campaign.",
        output: "It wrote the Meta ad in English and Hindi, launched it, and replaced the losing variant automatically.",
        control: "Campaigns are human-approved before launch. In development — not live today - GharGPT Conversational property discovery across the whole marketplace. - Negotiation Assists both sides through offer and counter-offer. - Visit Concierge Plans and coordinates multi-property site visits. - Agreement Explainer Explains a rental or sale agreement clause by clause. - Society Copilot Answers resident questions from the society's own records. - NRI Advisor Guides non-resident buyers through remote purchase and compliance. Roles ## Who TrustProperty is for 6 roles, each with its own view — and an audit log that records who saw what." },
    ],
    modules: [
      { title: "Search and discovery", body: "Buy, rent, PG and co-living, plots and land, and commercial space, with verified owner listings and RERA-ID checks." },
      { title: "TrustLine on every listing", body: "Grounded per-listing question answering in chat and real-time voice with interruption handling, continuing on WhatsApp, with site-visit booking in the conversation." },
      { title: "Owner tools", body: "Voice-dictated listing intake that fills the form and names the fields still missing, AI copy in English and Hindi, AI pricing from live comparables, and tenant screening before a phone number is released." },
      { title: "TrustProperty Pro for agents", body: "Lead intelligence with the reasoning shown, a deal pipeline with AI nudges, a WhatsApp-native inbox, AI marketing with human approval, and a brokerage ledger with TDS and GST e-invoicing." },
      { title: "Legal and verification services", body: "Encumbrance check from ₹1,499, title verification ₹5,999 and full due diligence ₹7,999 — each reviewed by a qualified lawyer with a risk-graded, digitally-signed report. Tenant verification from ₹99." },
      { title: "The full transaction lifecycle", body: "Beyond the deal: sale-deed drafting, sub-registrar registration and stamp duty, and post-registration Khata and mutation transfer." },
    ],
    roles: [
      { title: "Buyer or tenant", body: "Free. Verified search, TrustLine answering any listing 24×7, visit booking, valuation, home loans and EMI, and paid legal verification when it matters. Zero brokerage." },
      { title: "Owner or seller", body: "Free forever. Speak sixty seconds and the listing form fills itself, AI copy in English and Hindi, AI pricing from comparables, and tenant screening with fraud checks before your number is released." },
      { title: "Agent or agency", body: "TrustProperty Pro: lead scores with the reasons shown, a deal pipeline with AI nudges, portal and WhatsApp in one inbox, AI advertising with human approval, and a brokerage ledger with TDS and GST." },
      { title: "Builder or channel partner", body: "The full AI stack on a transparent paid plan, with territories and payout tracking." },
      { title: "Service professional", body: "Onboarding into the home-services marketplace with upfront pricing." },
      { title: "Society or RWA", body: "Society management surfaces for resident and community operations." },
    ],
    compliance: ["RERA-ID checks on listings", "DPDP Act 2023", "Profiling opt-out that halts the pipeline", "PII redacted before any model call", "Human review of AI-assisted outcomes", "Per-subsystem kill switches", "Data in India"],
    faqs: [
      { q: "What is TrustProperty?", a: "TrustProperty is an AI-native property platform for India — buying, renting, PG and co-living, plots and commercial space — with verified listings, zero brokerage, and TrustLine AI answering questions on every listing 24×7." },
      { q: "What is TrustLine?", a: "TrustLine is an AI concierge attached to every individual listing. It answers questions from that listing's own verified facts in text or real-time voice, handles interruptions mid-answer, works in English, हिंदी and Hinglish, continues the conversation on WhatsApp, and books site visits into the owner's live calendar." },
      { q: "Is the legal verification done by AI?", a: "No, and deliberately so. Title and encumbrance verification is reviewed by a qualified lawyer, never an automated scan, and returns a risk-graded verdict in a digitally-signed report. Packages start at ₹1,499 for an encumbrance check, ₹5,999 for title verification and ₹7,999 for full due diligence." },
      { q: "How is buyer and seller data protected?", a: "Personal information is redacted before any model call, so the models see the question rather than the person. Profiling opt-out halts the pipeline before any automated step, every AI-assisted outcome can be reviewed by a human, and each subsystem has a kill switch." },
      { q: "Which cities does TrustProperty cover?", a: "The launch focus is eight cities: Bengaluru, Mumbai, Pune, Hyderabad, Chennai, Delhi NCR, Kolkata and Ahmedabad." },
    ],
  },
};
